name: Release

on:
  workflow_dispatch:
  push:
    branches: mater

permissions: write-all
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

    #   - name: Setup SSH keys
    #     uses: shimataro/ssh-key-action@v2
    #     with:
    #       key: ${{ secrets.SSH_PRIVATE_KEY }}
    #       known_hosts: github.com

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup node cache
        id: node-cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: yarn-${{ hashFiles('yarn.lock') }}-${{ hashFiles('package.json') }}
          restore-keys: yarn-

      - name: Setup turbo cache
        uses: actions/cache@v3
        with:
          path: '.turbo'
          key: turbo-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.ref_name }}-
            turbo-master-

      - name: Install deps
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: yarn --ignore-scripts --prefer-offline --frozen-lockfile

      - name: Setup git
        run: |
          git config user.name "$GIT_USER_NAME"
          git config user.email "$GIT_USER_EMAIL"
        env:
          GIT_USER_NAME: ${{ vars.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ vars.GIT_USER_EMAIL }}

      - name: Release
        run: yarn release --cache-dir=.turbo
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}